from datetime import datetime, timedelta, timezone
import re

import jwt
from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError
from argon2.profiles import RFC_9106_LOW_MEMORY

from app.core.config import get_jwt_settings

_password_hasher = PasswordHasher.from_parameters(RFC_9106_LOW_MEMORY)


def hash_password(password: str) -> str:
    """Argon2id with a fresh random salt generated by the library."""
    return _password_hasher.hash(password)


def verify_password(password: str, password_hash: str) -> bool:
    try:
        return _password_hasher.verify(password_hash, password)
    except (VerificationError, InvalidHashError):
        return False


class InvalidAccessTokenError(Exception):
    """A credential-safe error for any rejected access token."""


def create_access_token(user_id: int) -> str:
    if type(user_id) is not int or not 1 <= user_id <= 2147483647:
        raise ValueError("Expected a valid User ID.")
    settings = get_jwt_settings()
    expires_at = datetime.now(timezone.utc) + timedelta(minutes=settings.expire_minutes)
    return jwt.encode(
        {"sub": str(user_id), "exp": expires_at},
        settings.secret_key,
        algorithm=settings.algorithm,
    )


def decode_access_token(token: str) -> int:
    """Verify the JWT and return a bounded integer matching users.id."""
    settings = get_jwt_settings()
    try:
        payload = jwt.decode(
            token,
            settings.secret_key,
            algorithms=[settings.algorithm],
            options={"require": ["sub", "exp"]},
        )
        subject = payload["sub"]
        if not isinstance(subject, str) or not re.fullmatch(r"[1-9][0-9]{0,9}", subject):
            raise InvalidAccessTokenError()
        user_id = int(subject)
        if user_id > 2147483647 or type(payload["exp"]) is not int:
            raise InvalidAccessTokenError()
        return user_id
    except (jwt.InvalidTokenError, ValueError, TypeError, OverflowError):
        raise InvalidAccessTokenError() from None
